Webbangiay/Webbangiay/Controllers/DonhangController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Webbangiay.Models;

namespace Webbangiay.Controllers
{
    public class DonhangController : Controller
    {
        Models.Model1 db = new Models.Model1();
        // GET: Donhang
        public ActionResult Index()
        {
            return View(db.Dathang.ToList());
        }

        // GET: Donhang/Details/5
       
        
        public ActionResult Details(String id)
        {
            return View(db.Dathang.Where(s => s.Madonhang.Replace(" ", "") == id).FirstOrDefault());
        }

        // GET: Donhang/Create
       

        // GET: Donhang/Edit/5
        public ActionResult Edit(String id)
        {
            return View(db.Dathang.Where(s => s.Madonhang.Replace(" ", "") == id).FirstOrDefault());
        }

        // POST: Donhang/Edit/5
        [HttpPost]
        public ActionResult Edit(String id, Dathang dh)
        {
            try
            {
                // TODO: Add update logic here
                db.Entry(dh).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Webbangiay/Webbangiay/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.IO;
using Webbangiay.Models;
using System.Data.Entity;

namespace Webbangiay.Controllers
{
    public class ProductController : Controller
    {
        Models.Model1 db = new Models.Model1();
        // GET: Product
        public ActionResult Index()
        {
            return View(db.Sanpham.ToList());
        }

        // GET: Product/Details/5
        public ActionResult Details(String id)
        {
            
            return View(db.Sanpham.Where(s=>s.Masp.Replace(" ", "") == id).FirstOrDefault() );
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            Sanpham sanpham = new Sanpham();
            return View(sanpham);
        }

        // POST: Product/Create
        [HttpPost]
        public ActionResult Create(Sanpham sp)
        {
            try
            {
                // TODO: Add insert logic here
                if(sp.ImageUpload!=null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(sp.ImageUpload.FileName);
                    string extension = Path.GetExtension(sp.ImageUpload.FileName);
                    if (extension != ".jpg" && extension != ".png" && extension != ".jpeg")
                    {
                        Response.Write("<script>alert('Vui lòng chọn file ảnh có đuôi jpg,png hoặc jpeg!')</script>");
                    }
                    else
                    {
                        fileName = fileName + extension;
                        sp.Anhsp = "~/Content/images/anhsp/" + fileName;
                        sp.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/images/anhsp/"), fileName));
                    }
                }
                db.Sanpham.Add(sp);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Edit/5
        public ActionResult Edit(string id)
        {
            return View(db.Sanpham.Where(s => s.Masp.Replace(" ", "") == id).FirstOrDefault());
        }

        // POST: Product/Edit/5
        [HttpPost]
        public ActionResult Edit(String id, Sanpham sp)
        {
            try
            {
                // TODO: Add update logic here
                if (sp.ImageUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(sp.ImageUpload.FileName);
                    string extension = Path.GetExtension(sp.ImageUpload.FileName);
                    if (extension != ".jpg" && extension != ".png" && extension != ".jpeg")
                    {
                        Response.Write("<script>alert('Vui lòng chọn file ảnh có đuôi jpg,png hoặc jpeg!')</script>");
                    }
                    else
                    {
                        fileName = fileName + extension;
                        sp.Anhsp = "~/Content/images/anhsp/" + fileName;
                        sp.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/images/anhsp/"), fileName));
                    }
                }
                db.Entry(sp).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Delete/5
        public ActionResult Delete(String id)
        {
            return View(db.Sanpham.Where(s => s.Masp.Replace(" ", "") == id).FirstOrDefault());
        }

        // POST: Product/Delete/5
        [HttpPost]
        public ActionResult Delete(String id, Sanpham sp)
        {
            try
            {
                // TODO: Add delete logic here
                sp= db.Sanpham.Where(s => s.Masp.Replace(" ", "") == id).FirstOrDefault();
                db.Sanpham.Remove(sp);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Webbangiay/Webbangiay/Controllers/ThuonghieuController.cs
using Webbangiay.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.IO;
using System.Data.Entity;

namespace Webbangiay.Controllers
{
    public class ThuonghieuController : Controller
    {
        // GET: Thuonghieu
        Models.Model1 db = new Models.Model1();
        public ActionResult Index()
        {
            return View(db.Thuonghieu.ToList());
        }

        // GET: Thuonghieu/Details/5
        public ActionResult Details(String id)
        {
            return View(db.Thuonghieu.Where(s => s.Mathuonghieu.Replace(" ", "") == id).FirstOrDefault());
        }

        // GET: Thuonghieu/Create
        public ActionResult Create()
        {
            Thuonghieu th = new Thuonghieu();
            return View(th);
        }

        // POST: Thuonghieu/Create
        [HttpPost]
        public ActionResult Create(Thuonghieu th)
        {
            try
            {
                // TODO: Add insert logic here
                if (th.ImageUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(th.ImageUpload.FileName);
                    string extension = Path.GetExtension(th.ImageUpload.FileName);
                    fileName = fileName + extension;
                    th.Logo = "~/Content/images/thuonghieu/" + fileName;
                    th.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/images/thuonghieu/"), fileName));
                }
                db.Thuonghieu.Add(th);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Thuonghieu/Edit/5
        public ActionResult Edit(String id)
        {
            return View(db.Thuonghieu.Where(s => s.Mathuonghieu.Replace(" ", "") == id).FirstOrDefault());
        }

        // POST: Thuonghieu/Edit/5
        [HttpPost]
        public ActionResult Edit(String id, Thuonghieu th)
        {
            try
            {
                // TODO: Add update logic here
                if (th.ImageUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(th.ImageUpload.FileName);
                    string extension = Path.GetExtension(th.ImageUpload.FileName);
                    fileName = fileName + extension;
                    th.Logo = "~/Content/images/thuonghieu/" + fileName;
                    th.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/images/thuonghieu/"), fileName));
                }
                db.Entry(th).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Thuonghieu/Delete/5
        public ActionResult Delete(String id)
        {
            return View(db.Thuonghieu.Where(s => s.Mathuonghieu.Replace(" ", "") == id).FirstOrDefault());
        }

        // POST: Thuonghieu/Delete/5
        [HttpPost]
        public ActionResult Delete(String id,Thuonghieu th)
        {
            try
            {
                // TODO: Add delete logic here
                th = db.Thuonghieu.Where(s => s.Mathuonghieu.Replace(" ", "") == id).FirstOrDefault();
                db.Thuonghieu.Remove(th);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Webbangiay/Webbangiay/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Webbangiay.Models;

namespace Webbangiay.Controllers
{
    public class UsersController : Controller
    {
        Models.Model1 db = new Models.Model1();
        // GET: Users
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(String id)
        {
            return View(db.Users.Where(s => s.Matk.Replace(" ", "") == id).FirstOrDefault());
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            Users us = new Users();
            return View(us);
        }

        // POST: Users/Create
        [HttpPost]
        public ActionResult Create(Users us)
        {
            try
            {
                // TODO: Add insert logic here
                if (us.ImageUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(us.ImageUpload.FileName);
                    string extension = Path.GetExtension(us.ImageUpload.FileName);
                    fileName = fileName + extension;
                    us.Avt = "~/Content/images/User/" + fileName;
                    us.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/images/User/"), fileName));
                }
                db.Users.Add(us);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Users/Edit/5
        public ActionResult Edit(String id)
        {
            return View(db.Users.Where(s => s.Matk.Replace(" ", "") == id).FirstOrDefault());
        }

        // POST: Users/Edit/5
        [HttpPost]
        public ActionResult Edit(String  id, Users us)
        {
            try
            {
                // TODO: Add update logic here
                if (us.ImageUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(us.ImageUpload.FileName);
                    string extension = Path.GetExtension(us.ImageUpload.FileName);
                    fileName = fileName + extension;
                    us.Avt = "~/Content/images/User/" + fileName;
                    us.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/images/User/"), fileName));
                }
                db.Entry(us).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Users/Delete/5
        public ActionResult Delete(String id)
        {
            return View(db.Users.Where(s => s.Matk.Replace(" ", "") == id).FirstOrDefault());
        }

        // POST: Users/Delete/5
        [HttpPost]
        public ActionResult Delete(String id, Users us)
        {
            try
            {
                // TODO: Add delete logic here
                us = db.Users.Where(s => s.Matk.Replace(" ", "") == id).FirstOrDefault();
                db.Users.Remove(us);
                db.SaveChanges();
                return RedirectToAction("Index");
           
            }
            catch
            {
                return View();
            }
        }
    }
}

Webbangiay/Webbangiay/Views/_LayoutPage1.cshtml
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="">
 <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Ela Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <link rel="apple-touch-icon" href="https://i.imgur.com/QRAUqs9.png">
    <link rel="shortcut icon" href="https://i.imgur.com/QRAUqs9.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/Content/assets/css/cs-skin-elastic.css">
    <link rel="stylesheet" href="~/Content/assets/css/style.css">
    <script src="~/Content/assets/js/script.js"></script>
    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
    <link href="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/jqvmap@1.5.1/dist/jqvmap.min.css" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/weathericons@2.1.0/css/weather-icons.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.css" rel="stylesheet" />


</head>

<body>
    <!-- Left Panel -->
    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">
            <div id="main-menu" class="main-menu collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="# "><i class="menu-icon fa fa-laptop"></i>Dashboard </a>
                    </li>

                    <li class="menu-item-has-children dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-list-alt"></i>Dữ Liệu Sản Phẩm</a>
                        <ul class="sub-menu children dropdown-menu">
                            <li><i class="fa fa-list"></i><a href="@Url.Action("Index","Product")">Tất Cả Sản Phẩm</a></li>
                            <li><i class="fa  fa-tasks"></i><a href="@Url.Action("Index","Thuonghieu")">Thương Hiệu</a></li>
                            <li><i class="fa fa-book"></i><a href="@Url.Action("Index","Donhang")">Đơn Hàng</a></li>
                        </ul>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Quản Lý Người Dùng<i class="menu-icon fa fa-users"></i></a>
                        <ul class="sub-menu children dropdown-menu">
                            <li><i class="fa fa-user"></i><a href="@Url.Action("Index","Users")">Danh Sách User</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </aside>22
    <!-- /#left-panel -->
    <!-- Right Panel -->
    <div id="right-panel" class="right-panel">
        <!-- Header-->
        <header id="header" class="header">
            <div class="top-left">
                <div class="navbar-header">
                    <a class="navbar-brand" href="@Url.Action("Index","Home")"><img src="~/Content/images/logo.png" alt="logo"></a>
                    <a class="navbar-brand hidden" href="@Url.Action("Index","Home")"><img src="~/Content/images/logo2.png" alt="logo"></a>
                    <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
                </div>
            </div>
            <div class="top-right">
                <div class="header-menu">
                    <div class="header-left">
                        <button class="search-trigger"><i class="fa fa-search"></i></button>
                        <div class="form-inline">
                            <form class="search-form">
                                <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">
                                <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
                            </form>
                        </div>
                    </div>

                    <div class="user-area dropdown float-right">
                        <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img class="user-avatar rounded-circle" src="~/Content/images/avatar/2.jpg" alt="User Avatar">
                        </a>
                    </div>
                </div>
            </div>
        </header>
        <!-- /#header -->
        <!-- Content -->
        <div class="col-md-10">
            @RenderBody()
        </div>
        <!-- /.content -->
        <div class="clearfix"></div>
        <!-- Footer -->
        <footer class="site-footer">
            <div class="footer-inner bg-white">
                <div class="row">
                    <div class="col-sm-6">
                        Copyright &copy; 2021 Huy ADMIN
                    </div>
                    <div class="col-sm-6 text-right">
                        LIÊN HỆ :
                        <a href="https://www.youtube.com/channel/UCAwNonyQevdBMD04cULCgBQ?view_as=subscriber"><i class="fa fa-youtube"></i></a>
                        <a href="https://www.youtube.com/channel/UCAwNonyQevdBMD04cULCgBQ?view_as=subscriber"><i class="fa fa-facebook"></i></a>
                        <a href="https://www.youtube.com/channel/UCAwNonyQevdBMD04cULCgBQ?view_as=subscriber"><i class="fa fa-instagram"></i></a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- /.site-footer -->
    </div>
    <!-- /#right-panel -->
    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
    <script src="~/Content/assets/js/main.js"></script>

    <!--  Chart js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.3/dist/Chart.bundle.min.js"></script>

    <!--Chartist Chart-->
    <script src="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartist-plugin-legend@0.6.2/chartist-plugin-legend.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/jquery.flot@0.8.3/jquery.flot.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flot-pie@1.0.0/src/jquery.flot.pie.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flot-spline@0.0.1/js/jquery.flot.spline.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/simpleweather@3.1.0/jquery.simpleWeather.min.js"></script>
    <script src="~/Content/assets/js/init/weather-init.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/moment@2.22.2/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.js"></script>
    <script src="~/Content/assets/js/init/fullcalendar-init.js"></script>

    <!--Local Stuff-->
    <script src="~/Content/assets/js/lib/data-table/datatables.min.js"></script>
    <script src="~/Content/assets/js/lib/data-table/dataTables.bootstrap.min.js"></script>
    <script src="~/Content/assets/js/lib/data-table/dataTables.buttons.min.js"></script>
    <script src="~/Content/assets/js/lib/data-table/buttons.bootstrap.min.js"></script>
    <script src="~/Content/assets/js/lib/data-table/jszip.min.js"></script>
    <script src="~/Content/assets/js/lib/data-table/vfs_fonts.js"></script>
    <script src="~/Content/assets/js/lib/data-table/buttons.html5.min.js"></script>
    <script src="~/Content/assets/js/lib/data-table/buttons.print.min.js"></script>
    <script src="~/Content/assets/js/lib/data-table/buttons.colVis.min.js"></script>
    <script src="~/Content/assets/js/init/datatables-init.js"></script>


    <script type="text/javascript">
        $(document).ready(function () {
            $('#bootstrap-data-table-export').DataTable();
        });
    </script>

</body>
</html>